stages:
- name: Build Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: jadcham/komposeui
      registry: index.docker.io
timeout: 60
notification:
  recipients:
  - recipient: '#monitoring'
    notifier: c-vb28v:n-qfh9x
  condition:
  - Success
  - Changed
  - Failed
