sudo: required
language: python
python:
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - curl -L https://github.com/kubernetes/kompose/releases/download/v1.0.0/kompose-linux-amd64 -o kompose && chmod +x kompose && sudo mv ./kompose /usr/local/bin/kompose
script:
  - python manage.py test
